import { useEffect, useState } from 'react';
import { RefreshCw } from 'lucide-react';
import api from '../api';

export default function AuditTrail() {
  const [filters, setFilters] = useState({ from: '', to: '', userId: '', action: '', entity: '' });
  const [users, setUsers] = useState([]);
  const [records, setRecords] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const load = async (next = filters) => { setLoading(true); setError(''); try { const { data } = await api.get('/audit-logs', { params: Object.fromEntries(Object.entries(next).filter(([, value]) => value)) }); setRecords(data); } catch (requestError) { setError(requestError.response?.status === 403 ? 'You do not have permission to view audit records.' : 'Unable to load audit records.'); } finally { setLoading(false); } };
  useEffect(() => { api.get('/users').then(({ data }) => setUsers(data)).catch(() => {}); load(); }, []);
  const change = (name, value) => setFilters((current) => ({ ...current, [name]: value }));
  const reset = () => { const clean = { from: '', to: '', userId: '', action: '', entity: '' }; setFilters(clean); load(clean); };
  return <section className="panel table-panel"><div className="section-heading"><div><div className="eyebrow">ADMIN / AUDIT TRAIL</div><h2>Audit trail</h2><p>Every sensitive action recorded by the operational system.</p></div><button className="secondary-button" onClick={() => load()} aria-label="Refresh audit records"><RefreshCw size={15} /> Refresh</button></div><div className="filter-bar"><label className="filter-control">From<input type="date" value={filters.from} onChange={(event) => change('from', event.target.value)} /></label><label className="filter-control">To<input type="date" value={filters.to} onChange={(event) => change('to', event.target.value)} /></label><label className="filter-control">User<select value={filters.userId} onChange={(event) => change('userId', event.target.value)}><option value="">All</option>{users.map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</select></label><label className="filter-control">Action<select value={filters.action} onChange={(event) => change('action', event.target.value)}><option value="">All</option><option value="LOGIN">LOGIN</option><option value="CREATE_ASSET">CREATE_ASSET</option><option value="UPDATE_ASSET">UPDATE_ASSET</option><option value="CREATE_PURCHASE">CREATE_PURCHASE</option><option value="UPDATE_PURCHASE">UPDATE_PURCHASE</option><option value="CREATE_TRANSFER">CREATE_TRANSFER</option><option value="CANCEL_TRANSFER">CANCEL_TRANSFER</option><option value="CREATE_ASSIGNMENT">CREATE_ASSIGNMENT</option><option value="CREATE_EXPENDITURE">CREATE_EXPENDITURE</option><option value="CREATE_USER">CREATE_USER</option><option value="UPDATE_USER">UPDATE_USER</option></select></label><label className="filter-control">Entity<select value={filters.entity} onChange={(event) => change('entity', event.target.value)}><option value="">All</option><option value="USER">USER</option><option value="ASSET">ASSET</option><option value="PURCHASE">PURCHASE</option><option value="TRANSFER">TRANSFER</option><option value="ASSIGNMENT">ASSIGNMENT</option><option value="EXPENDITURE">EXPENDITURE</option></select></label><button className="primary-small" onClick={() => load(filters)}>Apply filters</button><button className="secondary-button" onClick={reset}>Reset</button></div>{error ? <div className="alert error">{error} <button onClick={() => load()}>Retry</button></div> : loading ? <div className="table-state">Loading audit records...</div> : records.length === 0 ? <div className="table-state"><strong>No audit records found.</strong></div> : <div className="table-wrap"><table><thead><tr>{['Timestamp', 'User', 'Action', 'Entity', 'Entity ID', 'Metadata'].map((heading) => <th key={heading}>{heading}</th>)}</tr></thead><tbody>{records.map((record) => <tr key={record.id}><td>{record.timestamp}</td><td>{record.user?.name || '-'}</td><td>{record.action}</td><td>{record.entityType}</td><td>{record.entityId || '-'}</td><td>{record.metadata || '-'}</td></tr>)}</tbody></table></div>}</section>;
}
