spring.application.name=military-asset-management

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/military_asset_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.jpa.defer-datasource-initialization=false

spring.sql.init.mode=never
spring.main.allow-circular-references=true

app.cors.allowed-origins=http://localhost:5173
